version: '2'

services:

  web:
    image: webserver-nginx
    build: ./nginx
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - php

  php:
    image: webserver-php
    build: ./php
    volumes:
      - ./app:/app
    working_dir: /app

  mysql:
    image: mysql:5.7.21
    volumes:
      - ./app:/app
      - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /app

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    links:
      - "mysql:db"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_DATABASE=world
volumes:
  dbdata: